# **lists arrays identify type**

In [1]:
import numpy as np
list1 = [1,2,3]
list2 = [4,5,6]
array1 = np.array(list1)
array2 = np.array(list2)
array3 = np.array([[list1],[list2]])
# print(list1)
# print(array1)
type(list1)
type(array1)
print(array3)
type(array3)

[[[1 2 3]]

 [[4 5 6]]]


numpy.ndarray


# **mathematical operations (multiplication,division,poweroff) addition of two arrays(array1+array2)**

In [2]:
array_multiplication = np.multiply(list1,list2)
print(array_multiplication)
array_division = np.divide(list1,list2)
print(array_division)
array_poweroff = np.power(array1,array2)
print(array_poweroff)
text_output = f"Addition of wo arrays:{array1}+{array2} = {np.add(array1,array2)}"
print(text_output)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
Addition of wo arrays:[1 2 3]+[4 5 6] = [5 7 9]


# **# implement np.sin(),log(),log2(),np.exp()**

In [3]:
sin_values = np.sin(list1)
log2_values = np.log2(list1)
log_values = np.log(list1)
exp_values = np.exp(list1)
print(sin_values)
print(log2_values)
print(log_values)
print(exp_values)

[0.84147098 0.90929743 0.14112001]
[0.        1.        1.5849625]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
